language: node_js
node_js:
  - '0.10'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-co-hapi' ]; then cd .. && eval "mv $currentfolder generator-co-hapi" && cd generator-co-hapi; fi

